# Generated by Django 4.1 on 2022-10-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description_short",
            field=models.TextField(default="<Not provided>", max_length=1000),
        ),
    ]
