# Generated by Django 4.1 on 2022-10-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_description_short"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="concepts",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
